/*
* File:   band_stop.h
* Author: autogenerated
*
* Created on 
*/

#ifndef _BAND_PASS_ALU_H
  #define _BAND_PASS_ALU_H
  #define int_16_band_pass_alu short int
  #define int_32_band_pass_alu long int
  typedef struct {
      int nb_coeffs;
      int nb_states;
      int_16_band_pass_alu *coeffs;
      int_32_band_pass_alu *states;
  } s_16bits_filter_band_pass_alu;
  typedef s_16bits_filter_band_pass_alu *p_16bits_filter_band_pass_alu;
  /* creator of structure p_16bits_filter_band_pass_alu */
  extern p_16bits_filter_band_pass_alu new_16bits_filter_band_pass_alu(void);
  extern void destroy_16bits_filter_band_pass_alu(p_16bits_filter_band_pass_alu p_band_pass_alu);
  extern int_32_band_pass_alu one_step_16bits_filter_band_pass_alu(int_16_band_pass_alu en_16, p_16bits_filter_band_pass_alu p_band_pass_alu);
  typedef struct {
      int nb_cels;
      int nb_coeffs;
      int nb_states;
      double *coeffs;
      double *states;
  } s_real_filter_band_pass_alu;
  typedef s_real_filter_band_pass_alu *p_real_filter_band_pass_alu;
  extern double one_step_real_filter_band_pass_alu(double en, p_real_filter_band_pass_alu f);
  extern void destroy_real_filter_band_pass_alu(p_real_filter_band_pass_alu f);
  extern p_real_filter_band_pass_alu new_real_filter_band_pass_alu(void);
#endif /* _BAND_PASS_ALU_H */
