/*
* File:   band_stop.h
* Author: autogenerated
*
* Created on 
*/

#ifndef _BAND_PASS_H
  #define _BAND_PASS_H
  #define int_16_band_pass short int
  #define int_32_band_pass long int
  typedef struct {
      int nb_coeffs;
      int nb_states;
      int_16_band_pass *coeffs;
      int_32_band_pass *states;
  } s_16bits_filter_band_pass;
  typedef s_16bits_filter_band_pass *p_16bits_filter_band_pass;
  /* creator of structure p_16bits_filter_band_pass */
  extern p_16bits_filter_band_pass new_16bits_filter_band_pass(void);
  extern void destroy_16bits_filter_band_pass(p_16bits_filter_band_pass p_band_pass);
  extern int_32_band_pass one_step_16bits_filter_band_pass(int_16_band_pass en_16, p_16bits_filter_band_pass p_band_pass);
  typedef struct {
      int nb_cels;
      int nb_coeffs;
      int nb_states;
      double *coeffs;
      double *states;
  } s_real_filter_band_pass;
  typedef s_real_filter_band_pass *p_real_filter_band_pass;
  extern double one_step_real_filter_band_pass(double en, p_real_filter_band_pass f);
  extern void destroy_real_filter_band_pass(p_real_filter_band_pass f);
  extern p_real_filter_band_pass new_real_filter_band_pass(void);
#endif /* _BAND_PASS_H */
