CC=gcc -lm
CFLAGS=-Wall
main: main.o arbitrary.o high_pass.o low_pass.o band_pass.o band_stop.o statistics.o

clean:
	rm -f main main.o arbitrary.o high_pass.o low_pass.o band_pass.o band_stop.o statistics.o
